### PR TITLE
Error when combining name and indexed hole

### PR DESCRIPTION
**Pull request by 304NotModified**
Goals: 
1. stop parsing when there is something wrong, 
2.  when rendering, knowing that the template is valid

@jods4  let me hear your thoughts :)

### CODE REVIEW

**Comment by jods4** [comment]
If I understand correctly, you turned `{0} {x}` into an error?
I thought we would accept it as a template with _names_ "0" and "x".

**Comment by 304NotModified** [comment]
Well if we accept it, how should be render it? I think it makes things easier if we won't accept it (and that makes it more consistent work serilog). 

But if I missed something ;) let me know!

**Comment by jods4** [comment]
I had the following in mind: 
- a template in which _all holes are numbers_ will be rendered in `string.Format` compatible mode (each hole receive the parameter by index).
- a template in which _at least one hole is not a number_ will be rendered in named-mode: each hole receives the next parameter.

So I was going to render: `"{x} {0}", {"p1", "p2"}` as `"p1 p2"` or `{ "template": "{x} {0}", "params": { "x": "p1", "0": "p2" } }`.

**Comment by 304NotModified** [comment]
I think using {0} sometimes as index, and sometimes as named is really confusing. Also, it makes the code (rending) a bit more difficult IMO. 

I doubting, but I still vote for accept this PR. @adamchester, @nblumhardt, what are you guys think?

**Comment by adamchester** [comment]
I agree it's confusing, and makes it harder. However, I like the idea not crashing at runtime when logging. I prefer to find out about the bad template through a code analyser at design time, or warning at runtime, but still make the effort to log something.

**Comment by adamchester** [comment]
P.s. Serilog and message templates treat them as named if any are not positionals.

**Comment by 304NotModified** [comment]
Good point about the error handling!

So Serilog does support "{0} {name}"?

**Comment by jods4** [comment]
@304NotModified I am not sure in which way rendering is made harder by this? 
In fact, I would argue that _parsing_ would be slightly more complex because it would need to detect the condition of mixed numbers/names (not hard, but it currently doesn't).

The only case where it makes a big difference IMHO is if you try to render directly, without parsing to an intermediate structure first. 
Parsing the template makes sense if you plan on caching it, which should be the main scenario for us.
If you don't plan on caching and perform a one-shot render, it would be faster to render directly as you parse. In this context, when you see your first hole as `{1}` you have a problem: is this a named hole (parameter 0) or a positional hole (parameter 1). If mixing is not an error, you can't decide without looking ahead.

As I said, I don't think not parsing/caching is an option, so I don't think this matters a lot.

Regarding the error, I don't think it's worse that `Process {0} completes in {time}` throws compared to `Process {0} completes in 1}`, which throws as well. The worse is certainly `Process {0 completes in {1}` which doesn't throw but certainly doesn't do what you want.

**Comment by 304NotModified** [comment]
> @304NotModified I am not sure in which way rendering is made harder by this?

This is only true when we are combining named and numbers. But ifF we choose for, used indexed if**f** all are numbers, then there is no difference.

> The only case where it makes a big difference IMHO is if you try to render directly, without parsing to an intermediate structure first.

I pretty sure we need cache, but dunno how to do implement it ;)

> Process {0 completes in {1}

This will throw an error? Or not anymore?

**Comment by jods4** [comment]
> used indexed iff all are numbers, then there is no difference.

This is what we currently do, and from what @adamchester says I understand Serilog does the same.
I think that's fine.

> > Process {0 completes in {1}
> > This will throw an error? Or not anymore? 

This currently doesn't throw... it creates a capture with name `0 completes in {1` and I don't like it much.

**Pull request closed without merging**
