### PR TITLE
Init version

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by jods4** [comment]
Are you going for maximum perf? 
The parser code looks nice but it is not efficient. If you want to I can elaborate and comment on the code.

**Comment by 304NotModified** [comment]
Yes pref is indeed important! It's the first version, so it does need some improvements. 

I'm curious what is currently the most inefficient part in your opinion.

**Comment by 304NotModified** [comment]
@jods4  I added you as collaborator :)

**Comment by jods4** [comment]
@304NotModified Please have a look at my fork:
https://github.com/jods4/yamtp/blob/init/src/Parser/FastTemplateParser.cs
I created an equivalent parser based on your code but faster. It passes all your tests.

In my fork there is a benchmark as well (with just one random string):

``` ini

Host Process Environment Information:
BenchmarkDotNet=v0.9.8.0
OS=Windows
Processor=?, ProcessorCount=4
Frequency=3117797 ticks, Resolution=320.7393 ns, Timer=TSC
CLR=CORE, Arch=64-bit ? [RyuJIT]
GC=Concurrent Workstation
JitModules=?
dotnet cli version: 1.0.0-preview2-003121

Type=Program  Mode=Throughput  Toolchain=Core  
GarbageCollection=Concurrent Workstation  

```

| Method | Median | StdDev |
| --- | --- | --- |
| BaseParser | 2,320.8292 ns | 13.7305 ns |
| FastParser | 866.4542 ns | 4.6910 ns |

Memory allocations are down as well.

Why is it faster?
- Removed all iterators. They allocate on heap, require interface calls and are unlikely to be inlined. Moreover you were creating many iterators, sometimes just to read one character!
- Removed all StringBuilders. They allocate needlessly on heap. You were doing one-by-one char copies. If you're unlucky with the size of your strings your SB may have to expand (more allocs and copies). I am only using `Substring` which allocates only the target string and performs a `memcpy` (or its moral equivalent).

The design is to have short methods likely to be inlined (like `Peek`), use direct char access with an index in a basic loop and rely on the built-in, natively optimized string functions (`IndexOf`, `Substring`).

**Comment by 304NotModified** [comment]
Fantastic! Looks really great! 👍 👍   also thanks for the explanation!

**Comment by 304NotModified** [comment]
Could you send a PR?

**Comment by jods4** [comment]
@304NotModified Since you gave write access to the repo, I directly merged my faster parser into your branch.

**Comment by nblumhardt** [comment]
This is great :+1:

I'd like to have a shot at profiling and optimising a couple of things too, once this is merged (I think there could be some significant advantages to pursuing a struct-based `part` design, but need to tinker before I can come up with a decent proposal).

One thing you might consider; in Serilog I used the terms _destructuring_ and _destructuring operator_ (`@`) because the syntax was originally intended to have more sophisticated serialization abilities. In practice, this didn't turn out to be worth the syntactic complexity so it was never implemented, and we plug in policies to handle these scenarios instead.

Since that time I've been considering a proposal on the Serilog project to rename the concepts _capturing_ and _structure capturing operator_ which are closer in meaning to what the concept entails and generally should require less explanation.

Just a thought; I can see some benefits from us all being consistent, but it's also nice to start with a clean slate in a new implementation :-) (cc @AdamChester)

**Comment by adamchester** [comment]
> Since that time I've been considering a proposal on the Serilog project to rename the concepts capturing and structure capturing operator which are closer in meaning to what the concept entails and generally should require less explanation.

Great! The term destructuring has annoyed me :+1:

**Comment by 304NotModified** [comment]
> I'd like to have a shot at profiling and optimising a couple of things too, once this is merged (I think there could be some significant advantages to pursuing a struct-based part design, but need to tinker before I can come up with a decent proposal).

That would be great. It's indeed not in final state. Well merge this one then. 

> One thing you might consider; in Serilog I used the terms destructuring and destructuring operator (@) because the syntax was originally intended to have more sophisticated serialization abilities. In practice, this didn't turn out to be worth the syntactic complexity so it was never implemented, and we plug in policies to handle these scenarios instead.

I'm curious, do you have some examples of that?

> Since that time I've been considering a proposal on the Serilog project to rename the concepts capturing and structure capturing operator which are closer in meaning to what the concept entails and generally should require less explanation.

So stringify will be capture and destructure will be structure?

**Pull request merged**
